logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
spring:
  datasource:
    url: jdbc:mysql://47.105.166.190:3306/DB_WARNING_CONFIG?pinGlobalTxToPhysicalConnection=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: sky12580.
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
