spring:
  datasource:
    url: jdbc:mysql://192.168.163.128:3306/tztyw?pinGlobalTxToPhysicalConnection=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Niubi1234/
    driver-class-name: com.mysql.jdbc.Driver
